/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as RecipesNewIndexRouteImport } from './routes/recipes/new/index'
import { Route as ApiCartAddRouteImport } from './routes/api/cart/add'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as RecipesIdViewIndexRouteImport } from './routes/recipes/$id/view/index'
import { Route as RecipesIdEditIndexRouteImport } from './routes/recipes/$id/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewIndexRoute = RecipesNewIndexRouteImport.update({
  id: '/recipes/new/',
  path: '/recipes/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartAddRoute = ApiCartAddRouteImport.update({
  id: '/api/cart/add',
  path: '/api/cart/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdViewIndexRoute = RecipesIdViewIndexRouteImport.update({
  id: '/recipes/$id/view/',
  path: '/recipes/$id/view/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdEditIndexRoute = RecipesIdEditIndexRouteImport.update({
  id: '/recipes/$id/edit/',
  path: '/recipes/$id/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/cart/add': typeof ApiCartAddRoute
  '/recipes/new/': typeof RecipesNewIndexRoute
  '/recipes/$id/edit/': typeof RecipesIdEditIndexRoute
  '/recipes/$id/view/': typeof RecipesIdViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/cart/add': typeof ApiCartAddRoute
  '/recipes/new': typeof RecipesNewIndexRoute
  '/recipes/$id/edit': typeof RecipesIdEditIndexRoute
  '/recipes/$id/view': typeof RecipesIdViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/cart/add': typeof ApiCartAddRoute
  '/recipes/new/': typeof RecipesNewIndexRoute
  '/recipes/$id/edit/': typeof RecipesIdEditIndexRoute
  '/recipes/$id/view/': typeof RecipesIdViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipes/'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/cart/add'
    | '/recipes/new/'
    | '/recipes/$id/edit/'
    | '/recipes/$id/view/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recipes'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/cart/add'
    | '/recipes/new'
    | '/recipes/$id/edit'
    | '/recipes/$id/view'
  id:
    | '__root__'
    | '/'
    | '/recipes/'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/cart/add'
    | '/recipes/new/'
    | '/recipes/$id/edit/'
    | '/recipes/$id/view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiCartAddRoute: typeof ApiCartAddRoute
  RecipesNewIndexRoute: typeof RecipesNewIndexRoute
  RecipesIdEditIndexRoute: typeof RecipesIdEditIndexRoute
  RecipesIdViewIndexRoute: typeof RecipesIdViewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new/': {
      id: '/recipes/new/'
      path: '/recipes/new'
      fullPath: '/recipes/new/'
      preLoaderRoute: typeof RecipesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart/add': {
      id: '/api/cart/add'
      path: '/api/cart/add'
      fullPath: '/api/cart/add'
      preLoaderRoute: typeof ApiCartAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/view/': {
      id: '/recipes/$id/view/'
      path: '/recipes/$id/view'
      fullPath: '/recipes/$id/view/'
      preLoaderRoute: typeof RecipesIdViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/edit/': {
      id: '/recipes/$id/edit/'
      path: '/recipes/$id/edit'
      fullPath: '/recipes/$id/edit/'
      preLoaderRoute: typeof RecipesIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiCartAddRoute: ApiCartAddRoute,
  RecipesNewIndexRoute: RecipesNewIndexRoute,
  RecipesIdEditIndexRoute: RecipesIdEditIndexRoute,
  RecipesIdViewIndexRoute: RecipesIdViewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
